#SPDX-License-Identifier: MIT-0
---
# tasks file for aws-cli
- name: Download AWS CLI v2
  ansible.builtin.get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp/awscliv2.zip"
    mode: '0644'

- name: Unzip AWS CLI installer
  ansible.builtin.unarchive:
    src: "/tmp/awscliv2.zip"
    dest: "/tmp"
    remote_src: yes

- name: Install AWS CLI v2
  ansible.builtin.command: "./aws/install"
  args:
    chdir: "/tmp"
  become: yes
  changed_when: false

- name: Clean up AWS CLI installer files
  ansible.builtin.file:
    path: "/tmp/aws"
    state: absent

- name: Remove AWS CLI zip file
  ansible.builtin.file:
    path: "/tmp/awscliv2.zip"
    state: absent
