#SPDX-License-Identifier: MIT-0
---
# handlers file for jenkins
- name: Restart Jenkins
  ansible.builtin.include_tasks: tasks/restart.yml

- name: Configure default users
  ansible.builtin.debug:
    msg: "Configure default users"
