#SPDX-License-Identifier: MIT-0
---
# handlers file for jenkins
- name: restart jenkins via service
  ansible.builtin.service:
    name: jenkins
    state: restarted
  when: jenkins_restart_behavior == 'service'
