#SPDX-License-Identifier: MIT-0
---
# handlers file for jenkins
- name: restart jenkins via service
  ansible.builtin.service:
    name: jenkins
    state: restarted
  when: jenkins_restart_behavior == 'service'

- name: safe-restart jenkins via CLI
  ansible.builtin.command: java -jar {{ jenkins_jar_location }} -auth {{ jenkins_admin_username }}:{{ jenkins_admin_password }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }} safe-restart
  when: jenkins_restart_behavior == 'safe-restart'