#SPDX-License-Identifier: MIT-0
---
# tasks file for docker-cli
- name: Install Docker dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - ca-certificates
    - curl

- name: Add Docker repository key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository
  ansible.builtin.shell: |
    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable" | tee /etc/apt/sources.list.d/docker.list
  args:
    executable: /bin/bash
  become: yes

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker CLI
  ansible.builtin.apt:
    name:
      - docker-ce-cli
      - docker-compose-plugin
    state: present