---
- name: Converge
  hosts: all
  become: false
  gather_facts: true

  tasks:
    - name: Include certbot role
      ansible.builtin.include_role:
        name: certbot
      vars:
        certbot_organization: "Test Organization"
        certbot_common_name: "test.example.com"
