#SPDX-License-Identifier: MIT-0
---
# tasks file for jenkins installation on Debian
- name: Download Jenkins GPG key
  ansible.builtin.get_url:
    url: "{{ jenkins_repo_key_url }}"
    dest: "{{ jenkins_local_gpg_key }}"
    mode: '0644'
    force: true

- name: Add Jenkins repository
  ansible.builtin.apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: yes
  when: jenkins_repo_url | default(false)

- name: Install Jenkins
  ansible.builtin.apt:
    name: jenkins
    state: "{{ jenkins_package_state }}"

- name: Check if systemd is the active init system
  ansible.builtin.shell: "ps -p 1 -o comm="
  register: active_init_system
  changed_when: false

- name: Debug systemd availability
  ansible.builtin.debug:
    msg: "Active init system: {{ active_init_system.stdout.strip() }}"

- name: Overwrite systemd jenkins service file
  ansible.builtin.include_tasks: overwrite-systemd-service.yml
  when: active_init_system.stdout.strip() != 'systemd'

- name: Start and enable Jenkins service
  ansible.builtin.service:
    name: jenkins
    # pattern: /usr/share/java/jenkins.war
    state: started
    enabled: yes
    use: service
