---
- name: Include OS-Specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Define jenkins_local_gpg_key
  ansible.builtin.set_fact:
    jenkins_local_gpg_key: "{{ __jenkins_local_gpg_key }}"
  when: jenkins_local_gpg_key is not defined

- name: Define jenkins_repo_url
  ansible.builtin.set_fact:
    jenkins_repo_url: "{{ __jenkins_repo_url }}"
  when: jenkins_repo_url is not defined

- name: Define jenkins_repo_key_url
  ansible.builtin.set_fact:
    jenkins_repo_key_url: "{{ __jenkins_repo_key_url }}"
  when: jenkins_repo_key_url is not defined

- name: Define jenkins_pkg_url
  ansible.builtin.set_fact:
    jenkins_pkg_url: "{{ __jenkins_pkg_url }}"
  when: jenkins_pkg_url is not defined

- name: Include OS-Specific tasks
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Configure Jenkins settings
  ansible.builtin.include_tasks: settings.yml