#SPDX-License-Identifier: MIT-0
---
# tasks file for jenkins installation on Debian
- name: Download Jenkins GPG key
  ansible.builtin.uri:
    url: "{{ jenkins_repo_key_url }}"
    dest: "{{ jenkins_local_gpg_key }}"
    mode: '0644'
    force: true
  register: jenkins_get_gpg_key
  retries: 3
  delay: 5
  until: jenkins_get_gpg_key.status == 200

- name: Add Jenkins repository
  ansible.builtin.apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: yes
  when: jenkins_repo_url | default(false)

- name: Install Jenkins
  ansible.builtin.apt:
    name: jenkins
    state: "{{ jenkins_package_state }}"

# If the output is systemd, then the system is using systemd as the init system. Otherwise without systemd.
- name: Check if systemd is the active init system
  ansible.builtin.command: "ps -p 1 -o comm="
  register: active_init_system
  changed_when: false

- name: Debug systemd availability
  ansible.builtin.debug:
    msg: "Active init system: {{ active_init_system.stdout.strip() }}"

- name: Overwrite systemd jenkins service file
  ansible.builtin.include_tasks: overwrite-master-systemd-service.yml
  when: active_init_system.stdout.strip() != 'systemd'

# - name: Start Jenkins service
#   ansible.builtin.set_fact:
#     jenkins_restart_behavior: "service"
#   notify: Restart Jenkins service
#   changed_when: true

# - name: Flush handlers immediately
#   ansible.builtin.meta: flush_handlers
